[tool.poetry]
name = "py-scaffolding"
version = "0.0.1"
description = "Empty project"
authors = ["Nicholas Fiorentini <lordgordon@users.noreply.github.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pylint = "^2.6.0"
mypy = "^0.800"
bandit = "^1.7.0"
black = "^20.8b1"
isort = "^5.7.0"
pytest-bdd = "^4.0.2"
coverage = "^5.4"
Sphinx = "^3.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
